TRAIL_IMAGE = "assets/images/Pixel25px.png"
TRAIL_EMITTER = "assets/trail_effect.json"
BITMAP_FONT = "assets/test.fnt"
SPARK_IMAGE = "assets/images/Sparks.png"
BLAST_EMITTER = "assets/blast_effect.json"
FONT_CONFIG = { 'font': '64px Roboto', 'align': 'center' }
JUMP_SFX = "assets/audio/jump.mp3"
SWISH_SFX = "assets/audio/swish.mp3"
PLAYER_COLORS = [ 0x00ffee, 0xf235f2, 0xf2ff00 ]