TRAIL_IMAGE = "assets/images/Pixel25px.png"
TRAIL_EMITTER = "assets/trail_effect.json"
BITMAP_FONT = "assets/test.fnt"
SPARK_IMAGE = "assets/images/Sparks.png"
BLAST_EMITTER = "assets/blast_effect.json"